### PR TITLE
Loadmempool fuzz corpus

### PR DESCRIPTION
**Pull request by rajarshimaitra**
Some new fuzz corpus for loadmempool harness added in [PR#19259](https://github.com/bitcoin/bitcoin/pull/19259)

### CODE REVIEW

**Comment by Crypt-iQ** [comment]
I think you found a bug in github because there are 4608 changed files and the diff is +29, -0 so the counter might have overflowed.  Do you have the ability to run `afl-cmin` on the files you have, then you can just get the smallest set of files that gives the same coverage.

**Comment by practicalswift** [comment]
@Crypt-iQ I think the `+29 -0` line numbers refer to text files only. Binary files are skipped in that calculation :)

BTW, the merge of this PR depends on the merge of the PR https://github.com/bitcoin/bitcoin/pull/19259. Usually new seeds are added to this repo only after the corresponding fuzzer has been merged into Bitcoin Core `master`.

Before merging this seed PR I think it makes sense to run libFuzzer's `-merge=1 -use_value_profile=1` to trim the corpus in this PR. That is the seed minimization technique we've used in the past and I think it makes sense to keep using it (instead of say `afl-cmin`) so that we get a consistent measure of coverage over time :)

Minimizing the corpus would be a matter of:

```
$ mkdir smaller-set-of-files-giving-the-same-coverage/
$ test/fuzz/validation_load_mempool \
      -merge=1 \
      -use_value_profile=1 \
      smaller-set-of-files-giving-the-same-coverage/ \
      all-4608-files-in-this-pr/
# Submit only the files in smaller-set-of-files-giving-the-same-coverage/ as part of this PR :)
```

**Comment by MarcoFalke** [comment]
Are the inputs minimized already?

**Comment by MarcoFalke** [comment]
Closing for now due to inactivity

**Review by ytbigvinny27 — COMMENTED** [review]
~🤌🏽

**Pull request closed without merging**
