### PR TITLE
Add fuzz inputs from my servers and oss-fuzz

### PR DESCRIPTION
**Pull request by maflcko**
Doing this in a single commit to allow the fuzz engine to create a smaller set of files.

### CODE REVIEW

**Review by murchandamus — APPROVED** [review]
LGTM, appears to just add 30k odd new fuzz inputs

ACK 0dbdd5523d4c67fc185f174aa7dfbcc81e10ad6b

**Comment by murchandamus** [comment]
Sure, feel free to pull it in, that’s what I pushed the branches for! :)

**Comment by murchandamus** [comment]
> Ok, running that now.
> 
> Also, it looks like we are nearing the time limit here.
> 
> So, I'd say to merge this and then right after open the pull request to delete-nonreduced.sh?

Approach ACK

**Review by murchandamus — COMMENTED** [review]
I verified that the second commit only modifies a bunch of I2P. Both the first and the second commit’s I2P seeds pass on my machine:

```
➜  build git:(2023-10-refactor-coinselector-tests) ✗ FUZZ=i2p src/test/fuzz/fuzz ../../qa-assets/fuzz_seed_corpus/i2p                                                                     <<<
i2p: succeeded against 1247 files in 2s.
➜  qa-assets git:(main) ✗ git reset --hard 00c956e4a9c555da5640946ec28cdd5e501c0554
HEAD is now at 00c956e4a9c Add fuzz inputs from my servers, murch, and oss-fuzz
➜  build git:(2023-10-refactor-coinselector-tests) ✗ FUZZ=i2p src/test/fuzz/fuzz ../../qa-assets/fuzz_seed_corpus/i2p
i2p: succeeded against 1256 files in 2s.
```
:shrug:

The first commits seems to add a bunch of files into the `fuzz_seed_corpus` directly instead of one of the subfolders. Any idea what may have happened there?

**Comment by murchandamus** [comment]
Sorry, PEBCAK on the files. In my `tig` window, it dropped the fuzz target folder on some files in the change list, but not the others. I didn’t realize that it would present me different levels of the path in one list. :facepalm:
image. 

```
➜  qa-assets git:(main) ✗ git reset --hard maflcko/main                                   
HEAD is now at c764d6c7842 Revert i2p fuzz inputs to work around crash for now
➜  bitcoin git:(master) ✗ cd ../bitcoin/build                                            
➜  build git:(master) ✗ FUZZ=i2p src/test/fuzz/fuzz ../../qa-assets/fuzz_seed_corpus/i2p
i2p: succeeded against 1247 files in 27s.
➜  build git:(master) ✗ cd ../../qa-assets
➜  qa-assets git:(main) ✗ git reset --hard 00c956e4a9c555da5640946ec28cdd5e501c0554       
HEAD is now at 00c956e4a9c Add fuzz inputs from my servers, murch, and oss-fuzz
➜  qa-assets git:(main) ✗ cd -                                                            
~/Workspace/bitcoin/build
➜  build git:(master) ✗ FUZZ=i2p src/test/fuzz/fuzz ../../qa-assets/fuzz_seed_corpus/i2p
i2p: succeeded against 1256 files in 26s.
➜  build git:(master) ✗ 
```

I don’t know why it doesn’t crash on my machine but I can not replicate it crashing with either of your two commits here.

**Comment by hebasto** [comment]
Could this PR cause CI timeouts?

See: https://github.com/bitcoin/bitcoin/issues/28703.

**Pull request merged**
