### PR TITLE
Miniscript updates

### PR DESCRIPTION
**Pull request by darosior**

### CODE REVIEW

**Comment by darosior** [comment]
Oh, you've added some inputs for miniscript_string already. Interestingly it doesn't seem to conflict. I still need to merge mines in yours though.

**Comment by MarcoFalke** [comment]
It should never conflict, as the filenames are simply the hash of the file content

**Comment by MarcoFalke** [comment]
Though, it looks like you deleted my inputs? :sweat_smile:

**Comment by MarcoFalke** [comment]
Oh, maybe you moved all inputs (mine + yours) into a new folder and then merged the new folder into an empty folder? In that case not all inputs that were there originally are taken over.

**Comment by darosior** [comment]
I think i merged your folder into mine. What i'm doing now is merging both yours and mines at the same time in an empty folder:
```
FUZZ=.... ./empty_folder ./my_miniscript_script ./existing_miniscript_script
```
Does that sound right?

Also i'm using a branch from https://github.com/bitcoin/bitcoin/pull/24860#discussion_r893376746 that doesn't have the slowness of current master. I guess it shouldn't wreck the coverage, but maybe i should use master instead?

**Comment by MarcoFalke** [comment]
Generally I try to make adding inputs append-only.

You can achieve that by checking out the current main and then merging into the main folders.

For example, `FUZZ=miniscript_string ./src/test/fuzz/fuzz -merge=1 ../btc_qa_assets/fuzz_seed_corpus/miniscript_string  ./temp_ms_s/` or `./test/fuzz/test_runner.py -l DEBUG  -j 9 --m_dir ../btc_qa_assets/oss_fuzz_inputs/ ../btc_qa_assets/fuzz_seed_corpus`.

**Comment by MarcoFalke** [comment]
Obviously we still need to delete non-reduced inputs occasionally. Though, I am doing that separately: https://github.com/bitcoin-core/qa-assets/pull/82

Not sure if it is better to do both steps in the same pull.

**Comment by darosior** [comment]
Ok, that's what i was going to ask. :)

I ended up doing essentially what you said with one more step (merging into an empty dir and moving the seeds of the empty dir to `fuzz_seed_corpus/miniscript_script/`).

**Comment by MarcoFalke** [comment]
This was re-reverted (aka now merged) in aea795691ccb463ea6a6d071bf426acdf889ea5f

**Pull request merged**
