### PR TITLE
tests: Add seeds

### PR DESCRIPTION
**Pull request by practicalswift**
Add seeds.

### CODE REVIEW

**Comment by practicalswift** [comment]
Pushed another batch. Now at 972 files (was 805).

**Comment by practicalswift** [comment]
Another batch pushed. Now at 4269 files :)

**Comment by MarcoFalke** [comment]
Merged with 

```
time ./test/fuzz/test_runner.py ../btc_qa_assets/fuzz_seed_corpus -l DEBUG --m_dir ../btc_qa_assets/fuzz_seed_corpus_ps7
```

took 15 minutes

**Comment by practicalswift** [comment]
Excellent! Worth waiting for! :)

**Pull request closed without merging**
