### PR TITLE
Add seeds

### PR DESCRIPTION
**Pull request by practicalswift**
Add seeds.

### CODE REVIEW

**Comment by practicalswift** [comment]
Added seeds. Now at 1966 added files (was 1057).

**Comment by practicalswift** [comment]
Added seeds. Now at 5171 added files (was 1966).

**Comment by practicalswift** [comment]
Added seeds. Now at 6004 added files (was 5171).

**Comment by practicalswift** [comment]
@MarcoFalke Can I haz merge? :)

**Comment by MarcoFalke** [comment]
Merged with 

```
time ./test/fuzz/test_runner.py ../btc_qa_assets/fuzz_seed_corpus --par=9 -l DEBUG --m_dir ../btc_qa_assets/fuzz_seed_corpus_ps12/


...




real	3m20.396s
user	18m4.968s
sys	0m50.459s

**Comment by practicalswift** [comment]
Thanks! :)

**Pull request closed without merging**
