### PR TITLE
Initial corpus for the `miniscript_random` target

### PR DESCRIPTION
**Pull request by darosior**
It is introduced in https://github.com/bitcoin/bitcoin/pull/24149

### CODE REVIEW

**Comment by darosior** [comment]
Source-based coverage of the corpus: http://download.darosior.ninja/dump/coverage_miniscript_random/src/script/index.html

**Comment by MarcoFalke** [comment]
Ok. Is there another target where the files can be moved to or should I force push the commit away?

**Comment by MarcoFalke** [comment]
I've force pushed the merge away. Please open a fresh pull request with anything that should be done

**Comment by darosior** [comment]
My bad, i should have closed this PR long ago.. Thanks for noticing Sipa.

-------- Original Message --------

**Pull request merged**
