### PR TITLE
Add Murch’s fuzz seed in January 2024

### PR DESCRIPTION
**Pull request by murchandamus**

### CODE REVIEW

**Comment by murchandamus** [comment]
Nice. I did mine just with the regular merge script:

Run mini_miner with args […]/qa-assets/src/test/fuzz/fuzz -rss_limit_mb=8000 -set_cover_merge=1 -shuffle=0 -prefer_small=1 -use_value_profile=0 ../qa-assets/fuzz_seed_corpus/mini_miner ../qa-assets-active-fuzzing/fuzz_seed_corpus/mini_miner

**Comment by dergoegge** [comment]
Could you redo the merge on top of #163? (to avoid duplicates)

**Comment by murchandamus** [comment]
Sure, gimme a few hours.

**Comment by murchandamus** [comment]
I rebased on #163 and used @maflcko’s approach:

```
mv ../qa-assets/fuzz_seed_corpus /tmp/fuzz_inputs_upstream
./test/fuzz/test_runner.py --par $( nproc ) -l DEBUG ../qa-assets/fuzz_seed_corpus/ --m_dir ../qa-assets-active-fuzzing/fuzz_seed_corpus/ -x wallet_notifications -x utxo_total_supply --m_dir /tmp/upstream_fuzz_seed_corpus -x wallet_notifications -x utxo_total_supply
git restore -- ./fuzz_seed_corpus
git add ./fuzz_seed_corpus
git commit -S -m "Add fuzz seeds"
```

The test_runner script then used `-set_cover_merge=1 -shuffle=0 -prefer_small=1 -use_value_profile=0` under the hood.

**Pull request merged**
