### PR TITLE
Shrink descriptor_parse size, increase coverage

### PR DESCRIPTION
**Pull request by Sjors**
This shrinks the number of input files for `descriptor_parse`, and reduces storage from 234MB to 172MB.

libFuzzer options:
`-use_value_profile=1 -prefer_small=1 -shuffle=0`

`--with-sanitizers=address,fuzzer,undefined`

Bitcoin Core de1d1895346ed27f471386011d7ff64508f8b39c

After running the fuzzer for a bit, I moved the original input files into the directory where I kept my additional inputs, and then `-merge`'d back into the qa-assets directory.

Let me know if this methodology is sound*. If so, I'll run it a bit longer to see if that reduces storage more.

`*` = maybe not, because I only ran on my own architecture?

### CODE REVIEW

**Comment by Sjors** [comment]
cc @dergoegge @darosior

**Comment by darosior** [comment]
Can you generate a coverage report to make sure this did not in fact diminish coverage?

Maybe @MarcoFalke can give guidance too. I'm far from an expert about fuzzing.

**Comment by MarcoFalke** [comment]
No strong opinion, but I'd prefer if deleting inputs was only done every 6 months (before a release) with a script to aid review and reproducibility. See https://github.com/bitcoin-core/qa-assets/pull/97

**Comment by Sjors** [comment]
Happy to hold this in draft until closer to the release.

@sipa wrote in the other issue:

> I'd also suggest doing the minimization (create empty dir, -merge=1 into it) using both binaries with and without sanitizers - they tend to have different inputs that matter to them.

I re-ran the merge command on a binary with only the `fuzzer` sanitizer. This resulted in additional inputs, which I've pushed as a separate commit. It caused the inputs to grow to 260M, which is bigger than what this PR started with.

However, I had not run the fuzzer itself without sanitizers, so perhaps the merge could not find smaller inputs relevant for this configuration. The answer seems to be _no_, I ended up with 260M again.

So this approach doesn't scale well. 

Also, if then we also want to hold on to inputs that previously covered bugs, to catch a regression, the whole thing becomes a combinatorial explosion.

Perhaps it's best in practice if individual developers keep a larger corpus on their own machine(s). In particular, anytime this repo is pruned, they could hold on to the old inputs.

**Comment by MarcoFalke** [comment]
> Also, if then we also want to hold on to inputs that previously covered bugs, to catch a regression, the whole thing becomes a combinatorial explosion.

OSS-Fuzz does this already. Also, if a bug was found previously by a CPU, it will likely be found again, given enough CPU. So I don't worry too much about this. And if the "regression" input was invalidated anyway, holding on to it adds no value.

**Comment by MarcoFalke** [comment]
No need to close this. If there are inputs that add coverage, they can be added. Especially if they add line coverage or branch coverage.

**Comment by Sjors** [comment]
Should I drop the part that deletes existing inputs then?

**Comment by MarcoFalke** [comment]
See https://github.com/bitcoin-core/qa-assets/pull/104#issuecomment-1422579250

**Comment by Sjors** [comment]
That [maintainer script](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/main/delete_nonreduced_fuzz_inputs.sh) won't work here though. I didn't just merge existing inputs, I generated new ones. The only way to make that deterministic would be to first add all the new ones I generated, which would bloat the repo (my unmerged `descriptor_parse` corpus is 1 GB with less than an hour of fuzzing).

**Comment by dergoegge** [comment]
> > Also, if then we also want to hold on to inputs that previously covered bugs, to catch a regression, the whole thing becomes a combinatorial explosion.
>
> OSS-Fuzz does this already. Also, if a bug was found previously by a CPU, it will likely be found again, given enough CPU. So I don't worry too much about this. And if the "regression" input was invalidated anyway, holding on to it adds no value.

I think for targets that have a common input format (like a string that represents a descriptor for example), it could make sense to to make sure that initial seeds and "regression" inputs are not lost (which might happen when merging into an empty corpus). I guess this would mostly be relevant for inputs that can't be found by CPU, although making sure they aren't delted reduces the time to detect regressions, as they would immediately be caught in the CI.

**Comment by Sjors** [comment]
Come to think of it, for the purpose of the CI, we obviously only need to worry about the CI architecture and chosen set of sanitizers.

**Comment by MarcoFalke** [comment]
> The only way to make that deterministic

yeah, I don't think we need to make that deterministic. Just using libfuzzer to merge your 1GB folder into this repo should be good enough.

**Comment by MarcoFalke** [comment]
@dergoegge I guess there could be something like:


```
class CoverageAssertion{
bool m_coverage{
#ifdef ASSERT_COVERAGE
false
#else 
true // nothing to check
#endif 
};
~CoverageAssertion(){
assert(m_coverage);
}
void Set() {m_coverage=true;}
};
static CoverageAssertion g_coverage_assertion{};
```

And in the code:

```
if (condition) g_coverage_assertion.Set(); // covered this condition at least once
```

**Comment by MarcoFalke** [comment]
@Sjors Are you still working on this?

**Comment by Sjors** [comment]
Not at the moment, it's too unclear what the end result should look like. We I can keep it open until closer to the next release-branch off.

**Comment by MarcoFalke** [comment]
> it's too unclear what the end result should look like.

It should look like any other pull to this repo: `+x-0`

* https://github.com/bitcoin-core/qa-assets/pull/101
* https://github.com/bitcoin-core/qa-assets/pull/103
* ...

**Comment by Sjors** [comment]
I'll make a new PR to add the new inputs, because the whole point of this PR was to shrink the size, not to increase it. Alternatively I can wait until there's a way to safely prune.

**Comment by MarcoFalke** [comment]
> Alternatively I can wait until there's a way to safely prune

Pretty sure this isn't going to happen at all or at least any time soon.

**Comment by Sjors** [comment]
Ok, I'll run it a bit longer and with some other parameters and make a new PR soon(tm).

**Pull request closed without merging**
