### PR TITLE
Add fuzzing seeds to recently contributed fuzzing harnesses

### PR DESCRIPTION
**Pull request by practicalswift**
Add fuzzing seeds to recently contributed fuzzing harnesses.

Seeds for:
* https://github.com/bitcoin/bitcoin/pull/17050 – "tests: Add fuzzing harnesses for functions parsing scripts, numbers, JSON and HD keypaths (bip32)"
* https://github.com/bitcoin/bitcoin/pull/17051 – "tests: Add deserialization fuzzing harnesses"
* https://github.com/bitcoin/bitcoin/pull/17071 – "tests: Add fuzzing harness for `CheckBlock(...)` and other `CBlock` related functions"
* https://github.com/bitcoin/bitcoin/pull/17093 – "tests: Add fuzzing harness for various `CTx{In,Out}` related functions"
* https://github.com/bitcoin/bitcoin/pull/17109 – "tests: Add fuzzing harness for various functions consuming only integrals"
* https://github.com/bitcoin/bitcoin/pull/17136 – "tests: Add fuzzing harness for various PSBT related functions"
* https://github.com/bitcoin/bitcoin/pull/17229 – "tests: Add fuzzing harnesses for various Base{32,58,64} and hex related functions"

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Thanks, I will merge them with libFuzzer -merge=1

**Comment by MarcoFalke** [comment]
I found that only some script flags seeds increased coverage. See 3c3b16c3791a017299b6a75fee87bcf723da4dbd

**Comment by practicalswift** [comment]
@MarcoFalke That's expected since the script flags seeds I submitted were not bootstrapped with the seeds in the repo :)

Anything I need to do to get the others in? :)

**Comment by MarcoFalke** [comment]
All others didn't increase coverage for me. Feel free to double check

**Comment by practicalswift** [comment]
@MarcoFalke Please note that script flags was the only fuzzer in `master` that got added any seeds. The rest of the seeds are to fuzzers not yet merged (see linked PR:s).

Take `fuzz_seed_corpus/addr_info_deserialize/166c9b7e8a5d54837ddf5f752051c692115219ab` as an example. That is a fuzzer for `addr_info_deserialize` and AFAICT there are no seeds for that fuzzer in this repo, right? :)

**Comment by MarcoFalke** [comment]
Ah, thx

**Comment by practicalswift** [comment]
Can we move forward with adding the additional seeds? :)

**Comment by MarcoFalke** [comment]
I'd like to add them only after the fuzzers have been merged. Otherwise I can't calculate coverage information.

**Comment by practicalswift** [comment]
Is there anything I can do to get the fuzzers merged? :)

**Comment by MarcoFalke** [comment]
review on them would help

**Comment by practicalswift** [comment]
@MarcoFalke Can we move forward with some of the remaining fuzzing harnesses? :)

**Comment by MarcoFalke** [comment]
Thanks merged in 5c4e9f981ccd5a39a0a3b1093a9ad69117d28557

**Comment by MarcoFalke** [comment]
Let me know if I forgot some files which increase coverage, otherwise feel free to close

**Comment by MarcoFalke** [comment]
Before:

Screenshot_2019-12-18 LCOV - fuzz_coverage info

After:

Screenshot_2019-12-18 LCOV - fuzz_coverage info(1)

**Comment by practicalswift** [comment]
@MarcoFalke I'll investigate! To make sure we measure exactly the same way: what commands/options did you use to generate the coverage reports?

**Comment by MarcoFalke** [comment]
It looks like this:

```
Run prefilled_transaction_deserialize with args ...
... ['./src/test/fuzz/prefilled_transaction_deserialize', '-merge=1', '../btc_qa_assets/fuzz_seed_corpus/prefilled_transaction_deserialize', '../btc_qa_assets/fuzz_seed_corpus_other/prefilled_transaction_deserialize']
Output: INFO: Seed: 4151550544
INFO: Loaded 1 modules   (14253 inline 8-bit counters): 14253 [0x55a62cdea258, 0x55a62cdeda05), 
INFO: Loaded 1 PC tables (14253 PCs): 14253 [0x55a62cdeda08,0x55a62ce254d8), 
MERGE-OUTER: 417 files, 207 in the initial corpus
MERGE-OUTER: attempt 1
INFO: Seed: 4201440395
INFO: Loaded 1 modules   (14253 inline 8-bit counters): 14253 [0x5615a461a258, 0x5615a461da05), 
INFO: Loaded 1 PC tables (14253 PCs): 14253 [0x5615a461da08,0x5615a46554d8), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.14696.txt'
MERGE-INNER: 417 total files; 0 processed earlier; will process 417 files now
#1	pulse  lim: 4 exec/s: 0 rss: 33Mb
#2	pulse  lim: 4 exec/s: 0 rss: 33Mb
#4	pulse  lim: 4 exec/s: 0 rss: 33Mb
#8	pulse  lim: 4 exec/s: 0 rss: 33Mb
#16	pulse  lim: 4 exec/s: 0 rss: 34Mb
#32	pulse  lim: 4 exec/s: 0 rss: 37Mb
#64	pulse  lim: 4 exec/s: 0 rss: 44Mb
#128	pulse  lim: 4 exec/s: 0 rss: 51Mb
#256	pulse  lim: 4 exec/s: 0 rss: 59Mb
MERGE-OUTER: succesfull in 1 attempt(s)
MERGE-OUTER: the control file has 114441 bytes
MERGE-OUTER: consumed 0Mb (34Mb rss) to parse the control file
MERGE-OUTER: 0 new files with 0 new features added

**Comment by MarcoFalke** [comment]
So that is using libfuzzer. And libfuzzer is using "features" to determine if a seed adds coverage. You can get the "feature" coverage by just running libfuzzer. One of the lines will say:

```
#25	INITED cov: 714 ft: 1087 corp: 16/645b lim: 4 exec/s: 0 rss: 35Mb

**Comment by practicalswift** [comment]
@MarcoFalke I'm well aware of `libFuzzer` reports: I was thinking about what series of commands you ran to collect data for and to generate the `lcov` report. Trying to reproduce your results :)

**Comment by practicalswift** [comment]
Did you use `test/fuzz/test_runner.py`?

**Comment by MarcoFalke** [comment]
Oh :sweat_smile: 

https://github.com/MarcoFalke/btc_cov/blob/travis/.travis.yml

**Comment by MarcoFalke** [comment]
Hosted here: https://marcofalke.github.io/btc_cov/fuzz.coverage/index.html

**Comment by practicalswift** [comment]
Excellent! Exactly what I needed. Thanks!

**Pull request closed without merging**
