### PR TITLE
Add seeds

### PR DESCRIPTION
**Pull request by practicalswift**
Add seeds.

### CODE REVIEW

**Comment by practicalswift** [comment]
Added seeds to new (and some old) harnesses. Now at 7159 added seeds (was 1436).

**Comment by practicalswift** [comment]
Added seeds. Now at 7929 added seeds (was 7159).

**Comment by MarcoFalke** [comment]
I plan to hold back on merging this until we decided what to do with `std::optional`, as that might change the seed format for some fuzzers

**Comment by practicalswift** [comment]
@MarcoFalke I'm not sure I follow TBH: if we choose to do the `std::optional` change I'll have to re-create all the inputs for all the affected fuzzers regardless (and purge no longer needed inputs), so I don't see how having this PR merged would make the situation worse in any way? More coverage now is better than less coverage now, no? :)

**Comment by MarcoFalke** [comment]
I am not sure what the size limits on GitHub repositories are and I don't want them to shut this repo down. (The repo is append-only and deleting unused seeds is not going to reduce the size of the repo ever again, unless git history is rewritten)

**Comment by practicalswift** [comment]
@MarcoFalke 

FWIW I have hosted a monster size repo with the OS X source for many years at https://github.com/practicalswift/osx without any problems. AFAIK GitHub repos have a size limit of 100 GB, and GitHub handles repos with many millions of files without problems. In the past I've heard that repo search is disabled once you reach 500000 files in a repo, but everything else continues working as normal.

`qa-assets` is currently at a very modest 0.7 GB repo size with only 53825 files, so I think we'll reach the final goal of 100% fuzzing coverage with our inputs long before they fill up these GitHub limits :)

**Pull request merged**
