### PR TITLE
Add eleven initial corpora and new seeds

### PR DESCRIPTION
**Pull request by murchandamus**
Adds new seeds per same methodology as in #186 and adds initial corpora for the following eleven fuzz targets:

- clusterlin_add_dependency
- clusterlin_ancestor_finder
- clusterlin_chunking
- clusterlin_cluster_serialization
- clusterlin_depgraph_serialization
- clusterlin_linearization_chunking
- clusterlin_linearize
- crypter
- crypto_aeadchacha20poly1305
- crypto_fschacha20poly1305
- p2p_handshake

### CODE REVIEW

**Comment by murchandamus** [comment]
The number of lines added here seems off. Looking into what happened there.

**Comment by murchandamus** [comment]
I checked and my version of Bitcoin Core did not have that fuzz target, then realized that it just got merged yesterday. I can add it tomorrow to this PR after fuzzing it the next day or so.

**Comment by murchandamus** [comment]
Still around 240,000 new seeds, so I guess I didn’t do it wrong the first time after all.

**Comment by dergoegge** [comment]
> Still around 240,000 new seeds, so I guess I didn’t do it wrong the first time after all.

```
$ git diff --diff-filter=A --name-only origin/main..c98fc19a89d6c54a4b92d8e51a9b49d536d02ed2 | wc -l
1496
$ git diff --diff-filter=A --name-only origin/main..murch/2024-08-add-seeds | wc -l
19535
```

Only 1.5k new seeds for the new harnesses and about 20k new seeds in total, which seems fine.

I think the ~240k number refers to added lines (not sure how much sense that makes w.r.t fuzz inputs).

**Comment by murchandamus** [comment]
I see. I was assuming that any fuzz seed would be a single line

**Review by dergoegge — APPROVED** [review]
lgtm, waiting on CI

**Comment by murchandamus** [comment]
I have reverted the addition of seeds for the _utxo_snapshot_ target

**Pull request merged**
