### PR TITLE
Add fuzz seeds from 25rc1

### PR DESCRIPTION
**Pull request by Xekyo**
Draft: Testing whether I’m doing this right so far, before I throw more compute at fuzzing.

### CODE REVIEW

**Comment by Xekyo** [comment]
Yes, exactly, I was fuzzing with 25rc1. I’ve been fuzzing more while I was traveling, only to learn that libfuzzer appears to take the first of either `-runs` or `-max_total_time` and you can’t combine the two to make it stop whenever you hit one of the two limits. So… was fuzzing one thing for 35h, instead of everything for up to 20 minutes. Will merge my results on Monday and update this PR then.

**Comment by Xekyo** [comment]
Fuzzed every target for another 20 minutes.

**Comment by Xekyo** [comment]
Updated to remove `wallet_notification` fuzz seeds

**Comment by fanquake** [comment]
@dergoegge

**Review by dergoegge — APPROVED** [review]
lgtm

**Comment by Xekyo** [comment]
> Can't really find new coverage, but I guess it doesn't hurt too much either?
> 
> lgtm

I’m confused. If these new files didn’t increase the coverage, why did the merge not remove them? Did I do it wrong? :-/

**Pull request merged**
