### PR TITLE
Add seeds to fuzzers in master

### PR DESCRIPTION
**Pull request by practicalswift**
Add seeds to fuzzers in `master`.

### CODE REVIEW

**Comment by practicalswift** [comment]
There are a few coverage duplicates in this batch - sorry about that! Luckily `libFuzzer`'s `-merge` will take care of that :)

**Comment by practicalswift** [comment]
Pushed another batch of cases :)

**Comment by practicalswift** [comment]
@MarcoFalke I think we'll see a fantastic bump in fuzzing coverage once these test cases are merged :)

**Comment by MarcoFalke** [comment]
Thanks. Merged with `./test/fuzz/test_runner.py  ../btc_qa_assets/fuzz_seed_corpus -l DEBUG --m_dir ../btc_qa_assets/fuzz_seed_corpus_ps_6/`

**Comment by MarcoFalke** [comment]
total fuzz coverage up to 43% :rocket:

**Pull request closed without merging**
