### PR TITLE
Delete non-reduced fuzz inputs

### PR DESCRIPTION
**Pull request by MarcoFalke**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Can be "reproduced" with:

```
apt update
apt install wget -y
wget https://raw.githubusercontent.com/bitcoin-core/bitcoin-maintainer-tools/master/delete_nonreduced_fuzz_inputs.sh
bash delete_nonreduced_fuzz_inputs.sh

**Comment by laanwj** [comment]
Github is completely baffled by the size of the diff :see_no_evil:

**Comment by MarcoFalke** [comment]
I ran this twice and the difference was 7000 files, which is expected, because our fuzz targets are not deterministic

**Comment by fanquake** [comment]
> Would be nice if someone could test #44

I ran this and it seemed to achieve something similar to this PR; reducing the seed count by ~80'000:
```bash
# master @ 3038a21dd7d6dfb3574401b8c76e48ca87c44769
find . -type f | wc -l
241321

./ delete_nonreduced_fuzz_inputs.sh
# git log
commit f08f63d6121d794b18213f71ead508649055a493 (HEAD -> master)
Author: delete_nonreduced_inputs script <noreply@noreply.noreply>
Date:   Thu Jan 28 08:47:11 2021 +0000

    Reduced inputs for fuzzer,address,undefined,integer

commit 12116b05479ba817f0b9c98e00ae3ddf47f0fbe3
Author: delete_nonreduced_inputs script <noreply@noreply.noreply>
Date:   Thu Jan 28 07:42:43 2021 +0000

    Reduced inputs for fuzzer

commit c9e492d4d9c1281aeb107b027205f895b35d6ec9
Author: delete_nonreduced_inputs script <noreply@noreply.noreply>
Date:   Thu Jan 28 07:26:52 2021 +0000

    Delete fuzz inputs

commit 3038a21dd7d6dfb3574401b8c76e48ca87c44769 (origin/master, origin/HEAD)

# find . -type f | wc -l (my reduced branch)
163311

# find . -type f | wc -l ( this branch @ ae401aa90e5e3fa996b4066cb067f23a26e51a4d) 
163242
```

**Comment by MarcoFalke** [comment]
Ok, going to merge. If something went wrong, it is easy to revert.

**Comment by practicalswift** [comment]
Post-merge ACK ae401aa90e5e3fa996b4066cb067f23a26e51a4d: nice! :)

**Pull request merged**
