### PR TITLE
descriptor_parse: extend coverage with Miniscript Descriptors inputs

### PR DESCRIPTION
**Pull request by darosior**

### CODE REVIEW

**Comment by MarcoFalke** [comment]
There is already basic coverage: https://github.com/bitcoin-core/qa-assets/tree/main/fuzz_seed_corpus/descriptor_parse

So I presume you are extending it?

**Comment by darosior** [comment]
Hmm, i'm not so good at english. What i meant here was to add initial coverage for miniscript descriptors, but yeah, it is extending the descriptors coverage with new inputs (those that contain miniscripts inside).

**Comment by darosior** [comment]
Added some more seeds i've been generating in the background the past week(s). As a commit since it's not specific to Miniscript descriptors, it's extending the whole `descriptor_parse` corpus.

Marking as ready now that https://github.com/bitcoin/bitcoin/pull/24148 is merged (:tada:).

**Comment by darosior** [comment]
(I used a rebased https://github.com/bitcoin/bitcoin/pull/25540 to generate and merge those.)

**Comment by darosior** [comment]
How did you trigger this? I couldn't reproduce with `--with-sanitizers=fuzzer,undefined` running 
```
FUZZ=descriptor_parse ./src/test/fuzz/fuzz ../qa-assets/fuzz_seed_corpus/descriptor_parse -runs=0
```
on `088e5b0b9317bd1d7c9755fb839b7326d99bc910` (https://github.com/bitcoin/bitcoin/pull/25540's tip).

**Comment by MarcoFalke** [comment]
It needs the `integer` sanitizer, which is *not* the UB sanitizer. :sweat_smile: 

The input that triggers this is `./4a30defd5a644721859db1781153d0fb34decd94`.

**Comment by darosior** [comment]
Err, right.. :sweat_smile:
I've opened a PR fixing the wrap-around: https://github.com/bitcoin/bitcoin/pull/25642.

**Comment by darosior** [comment]
Yes, we need https://github.com/bitcoin/bitcoin/pull/25540 in first

**Pull request merged**
