### PR TITLE
Add Murch’s fuzz seeds June 2024 (2nd attempt)

### PR DESCRIPTION
**Pull request by murchandamus**
I tried a variant of the prior approach. I moved the upstream seeds to a separate directory, created a `set_cover_merge` from the existing and the new seeds from scratch, then restored the upstream entries.  
After that I did a second `set_cover_merge` with the target directory already having the resulting seeds from first merge. I found that it added seeds to several targets that increased the feature count, but on a few targets also increased coverage.

```
mv fuzz_seed_corpus fuzz_inputs_upstream
test/fuzz/test_runner.py -l DEBUG --par $( nproc ) --m_dir ./fuzz_inputs_upstream/  --m_dir ./active-fuzzing      fuzz_seed_corpus
git restore -- ./fuzz_seed_corpus
test/fuzz/test_runner.py -l DEBUG --par $( nproc ) --m_dir ./fuzz_inputs_upstream/  --m_dir ./active-fuzzing      fuzz_seed_corpus
git add ./fuzz_seed_corpus
git commit -m "Add Murch’s fuzz seeds June 2024"
```

I also did some additional fuzzing for `timeoffsets` and `scriptpubkeyman` given their recent updates.

### CODE REVIEW

**Comment by murchandamus** [comment]
Perhaps it found some significantly longer seeds that increase the coverage but take longer to run?

**Comment by murchandamus** [comment]
I could merge the `package_rbf` seeds again with a lower limit?

**Comment by murchandamus** [comment]
I realized that `wallet_bdb_parser` got added and fuzzed it a bit last night. Just added the seeds in a second commit.

**Comment by murchandamus** [comment]
>```
> SUMMARY: UndefinedBehaviorSanitizer: implicit-signed-integer-truncation wallet/migrate.cpp:554:35 
> ```

That’s odd, my fuzzer is generally configured with ` --with-sanitizers=address,fuzzer,undefined`

**Comment by murchandamus** [comment]
One downside of only submitting every two months is that I rediscover every time how all of this actually works. :sweat_smile:

Turns out that past-murch had created two different instances of his fuzz branch, where one `qa-fuzz` is running with a more lenient configuration, and the other `qa-merge` has all the sanitizers.

I am now redoing the merge with all sanitizers. I then will manually re-merge `package_rbf` enforcing a shorter limit for the seeds.

**Comment by murchandamus** [comment]
As discussed, I removed the two problematic seeds for the moment. I used a separate commit to make it easy to revert the removal, when the underlying issue has been addressed.

**Comment by dergoegge** [comment]
There is still one or more ISan triggering inputs in the `wallet_bdb_parser` corpus

**Pull request merged**
