### PR TITLE
Add seeds

### PR DESCRIPTION
**Pull request by practicalswift**
Add seeds.

I think we're reaching the point where it is hard to increase fuzzing coverage significantly via fuzzing along, so to reach significant additional coverage going forward I think we'll have to add more harnesses to `master`.

Review welcome for the following fuzzing harnesses awaiting review: https://github.com/bitcoin/bitcoin/pulls/practicalswift :)

### CODE REVIEW

**Comment by Crypt-iQ** [comment]
Do you think there's any benefit to running a minimization tool like `afl-cmin` or `afl-tmin` on the seeds? It can give faster startup times if there are a ton of redundant seeds, though I wonder if there's case to be made for a huge pool of diverse inputs.

**Comment by practicalswift** [comment]
@Crypt-iQ Yes, corpus minimization is good! The corpus is trimmed using libFuzzer's `-use_value_profile=1 -merge=1` both locally before I submit the PR, and sometimes also before merge when MarcoFalke runs the merge script.

That means that only coverage increasing inputs should be added (with some hopefully rare exceptions with non-deterministic harnesses where `-merge=1` is not stable for obvious reasons) :)

**Comment by Crypt-iQ** [comment]
Ah I see, that explains why afl-cmin trimmed it so much! I wonder if one minimization algorithm has a benefit over the other... might be worth comparing

**Comment by practicalswift** [comment]
@Crypt-iQ I believe libFuzzer's `-merge=1` combined with `-use_value_profile=1` is the current gold standard. It is what ClusterFuzz (and thus OSS-Fuzz) is using: see [`corpus_pruning_task.py`](https://github.com/google/clusterfuzz/blob/f89a0bfd6f127fe09a60c091ef7bf35c2a19c565/src/python/bot/tasks/corpus_pruning_task.py#L90-L91).

**Pull request merged**
